#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Rutas para el controlador: User #

user:
   path: /user
   controller: App\Controller\UserController::index

register:
   path: /register
   controller: App\Controller\UserController::create
   methods: [POST]  

login:
   path: /login
   controller: App\Controller\UserController::login 
   methods: [POST] 

user_edit:
   path: /user/edit
   controller: App\Controller\UserController::edit
   methods: [PUT]      

# Rutas para el controlador: Sucursal #

sucursal:
   path: /sucursal
   controller: App\Controller\SucursalController::index


# Rutas para el controlador: Empleado #

empleado:
   path: /empleado
   controller: App\Controller\EmpleadoController::index

# Rutas para el controlador: Area #

area:
   path: /area
   controller: App\Controller\AreaController::index 
   # methods: [POST]  

# Rutas para el controlador: Puesto #

puesto:
   path: /puesto
   controller: App\Controller\PuestoController::index    
