#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Rutas para el controlador: User #

user:
   path: /user
   controller: App\Controller\UserController::index

# Rutas para el controlador: Sucursal #

sucursal:
   path: /sucursal
   controller: App\Controller\SucursalController::index


# Rutas para el controlador: Empleado #

empleado:
   path: /empleado
   controller: App\Controller\EmpleadoController::index

# Rutas para el controlador: Area #

area:
   path: /area
   controller: App\Controller\AreaController::index 
   # methods: [POST]  

# Rutas para el controlador: Puesto #

puesto:
   path: /puesto
   controller: App\Controller\PuestoController::index    
